apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: eapol-operator-authenticator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authenticator-role
subjects:
- kind: ServiceAccount
  name: authenticator
  namespace: system
