apiVersion: v1
data:
  1x-ca.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRakNDQWlxZ0F3SUJBZ0lVU0w3dn
    ZDVUt2OHBwUE45WjQzY2NVS3hnVy9Jd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0V6RVJNQThH
    QTFVRUF3d0laR05oY21GMGRHa3dIaGNOTWpJd01URXpNRGd6TkRFNFdoY05Nekl3TVRFeA
    pNRGd6TkRFNFdqQVRNUkV3RHdZRFZRUUREQWhrWTJGeVlYUjBhVENDQVNJd0RRWUpLb1pJ
    aHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTFp0UTBoQXZ0V3hPUTBVaE5zNWNBNT
    Q2VlBGU0w2UHZoanN3YThkN0hienNZMDgKZy80TUgvbXYycnppTVU5dC9BU1o1NTNnQ3N4
    NDN5VG8yU2puV1VFRzRNQ002bitIalFwQVBGd1Z1TDlPai9IdgpyMmhxOHg3cEo2ZVY3OW
    pDRVdnVTJDaGE4aFROSVRDdERKbXByazBadS80UG45dWRLdUhWc05KcnFSYWlFMHZUCkNl
    S3kwalh2NHdHVFNaZnJycU5TUWNBNTZLaXpDK1lDaWEvY0FYK3piVU1yWFBpM3lDNFpFWX
    IxT1ZrekpNMEkKdDJmQklIdTNhejY3OUhPcjZlMElrRHJNQ2VZS2JzMjFtMFVLOUlGWjZS
    Z09XOXlCZU12RHN6czBPaWZ5MnoycQoxVFRxUWtkbVFwQ0Z0TExqSGdVaFp5TlRMc1hIeG
    c2UWtEZUNMUVVDQXdFQUFhT0JqVENCaWpBZEJnTlZIUTRFCkZnUVVWV2lKbXN6L3plZ29t
    S3pzdTM3VEg2YXVzOTR3VGdZRFZSMGpCRWN3UllBVVZXaUptc3ovemVnb21LenMKdTM3VE
    g2YXVzOTZoRjZRVk1CTXhFVEFQQmdOVkJBTU1DR1JqWVhKaGRIUnBnaFJJdnUrOEpRcS95
    bWs4MzFuagpkeHhRckdCYjhqQU1CZ05WSFJNRUJUQURBUUgvTUFzR0ExVWREd1FFQXdJQk
    JqQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBS05hYVpnWDMyaEVmSzZLZndnem1sNUJl
    WkVmTDg3eC85OGNueXNJVVh2cmZ5V0c1ZWhGaktGOGoKVlJieDZPWFRnWmt6S2lrUGlFd3
    VJZ0phNUwxWWFxNjFQQUZPVGJwSFZCbFV0TnRWMnlydU1rcmY2MkxVR25IaApqWmZVeGtY
    R2t2VDc5WTRVRDdTZGZNdk82T3lNVTd4akdVWkNaTEZYOEZBMEZFSDU1dSs1UmpKbkx6YX
    J0alhjClljeVVYVEJYZndWZGJVS0dZYStjbCtFbmtQZFA3OUNUaEV5eUJjZFQ0K01lUHpD
    OC9Zb2lLUUZjdjZMRDY1eEcKNk14RkVwQVMyWEZabGhIcm05SVBSWDdTT0lEWVNCZUZSRT
    JZN2JEcFBmRGJ2aDZKUGVpVy9SQnZxeGR4dXJZMwphbUVFbDZXYTZOajBhZml2d0ZYQjNY
    TThxVWwwNXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  1x-hostapd.example.com.key: |
    LS0tLS1CRUdJTiBFTkNSWVBURUQgUFJJVkFURSBLRVktLS0tLQpNSUlGSERCT0Jna3Foa2
    lHOXcwQkJRMHdRVEFwQmdrcWhraUc5dzBCQlF3d0hBUUlkNVZvRE9oNFBERUNBZ2dBCk1B
    d0dDQ3FHU0liM0RRSUpCUUF3RkFZSUtvWklodmNOQXdjRUNDajJLREhacVJRSEJJSUV5Q2
    psTEFtZ2Q2ZngKdHkzd0F4RDdqSjFXbExpY3BzVlpIUXphQXdyRUlkeFdCM3FKWFg3WFJ5
    TEpvc0tFZ0Q4M09pVmpYcUIwTzJHegpEaWJXRk03NUZ5UlZvMjRoai92QkdGODN5VnhMMW
    NaSXRlYjgxYjNqYVBFOHVGZkVobVlPRHRIb01XZUJVdm80CkYrSytCL2dxR2ZlczAraWUy
    bE5tWWJpeUh5RGwyUEdsSE10Qm4zZE0veGV6WmR2alRYOGdmVDZrZmhkV3ZRbXgKYWRKSG
    hNOWoxVUFhNUJ3bm91ZjhvekFZNHZlWm1IU0hrY3VycEtzVnFyRHNURk9mT2NLU2dabEF5
    WS9VN1FxVgp1NzZxd3lVOUttdEVvSU5WV3JMSHU4N2t3dXJnV2lnNjNrd0gzSFkwSlJlSn
    FFcEZjWTgwb2xKdjNLQnlrNmJRCms4RDREZ0RCR1FwS0VmUWVLVlRQUHVyZVRQbmgzZmVn
    Q3VnSGlXMWNxNUlpUjkvT3VwenNBVWFWek9QVStGdmgKczF4eGt0eUl1VmJRMTQwTlZ3bT
    g4UEl3aXdYZWQybnFuL1l3d21tYTNZeGdBV3h4MHZsNmNoNy9GSEZzRVBSQQpRUWpzL3JF
    RENsUGRIMmlYRy9lUzlPdE8rZjB2L1lSNStCdUVEd2YvSkZyNFhZWDN2a1dGNU02Z3E0WW
    11TG4yCnd5d1BxSkxVdUhlT0kzS2loS01MZEJpMFNNL1ovU1NqSGFqNmV6bFhRdlF1N1hX
    dmFJTVpXQTl2alJScXZnb2wKVEdMcUpGUncwSlVLcGovSE96ekRMNzBUdkx1L0krbnhxWm
    p0d0xZRGRLQ05pRGcrMUV1VndodGlNS2Y1MmY3egpNN3AzVC9HRG1aRnVWRXZwdTRSM005
    ZDUzb3c3MW96TkFEakhWMFlzNTk2S2x1Wnl3MmtpWnE4M3FwRUhPZEtlClJLeUlxZjVnWG
    ZOOTF6WDh4RUNTYlVXODVzZEhwa1JaaEh6YlUzcHNXLzdKM2xFVmxjVHJqMlFYYWRXNktE
    MEYKNWtRRjVVbUdYZXF5aXdmQ2x1YURVV1lwTGRMcEZLSzBvaWV1MHQ4b01GdFB3SHUrNm
    VkQmlBZDlXR1N0MW04dwpFN0t2MENxU1gyZEwxYi8yd1pFdkR3c2RoN2gzVUw0VFdiTWNH
    UE9KS21VMU9UazNzVmhvZTV0a0ZhNWZEazJVCm5oZkZBSW1tcFM4RU1JTzFMN0x5ZVBzK2
    9IOVFMYzBjSkFVT1ZjRW1zd2NsRWR1cDFjYkNLWmVQa2h3Y2FSZHkKaHJzcEtYTFNVRDBB
    K0c5aEpkSmtFOXpKTll6RkRlWFIvQmw5aWt5ejd6ejhJN2xNT2dvZzJrNm9vVndCRWxySg
    owRGNtSk9lVXdBcEc4ZEtuMy9ycFUzWjlSR1FtNlA3YklzOGMwYzNJdzkzenZHcFhJd1c3
    SXJlWkE5cE9TOW04CmRKMGQyM2JRc3djdzNlVEpPYmRlYnZtanVCUGlSZnVsNzA2U1NRd1
    d5c21uMW9CMkJabGFqOXRQZGhxbGEyTTkKK29oaEVPWVZ4TFUvdytybU41UkJKS2E4SkYr
    eDdqTEIxN0w3Q3RxcXRZWXkzSTBLeC9KVENVbTNLSXhZaUthbwptT3FnR3R3b3prd21VVH
    VkOGwrZG1iYUx5Y0dBSmpzbjlya3p0c0lublFwd2lNWjQyaFREZ0U3bU9hL2Q4cnYyCnE4
    OFF4OC9RbHgxV3dJM3lNWXpiTUkzNTAwbFpEUnZJQVJiYWRiVUIxOStmMjJEb2RqZUtEeH
    h4Tk9GNjR6MDEKbVFkMVhndGprQU0vZWZCLy9rQ3NSWVlEN0JoV3I5clFzTHdYZFdBa0VI
    ZitQajhIalVvUGwrT2RnT0RrOTVicgpVbHRZK3RKRjkwbjU4KzZXY3ZtNjVRWXFwTmpqeV
    hucDJRUUU4STBpY0ZvUFJXVUdVZ1c1eU1SRzFpdVJqakRtCkxuQ2lVVEkwYU1oQmw5Ym1T
    Nnl0dDA0eFBacXNGV3czQ3BlMzZqOU5qL0tNeVBCaVNydFdTaHYyaTRSUkt0Y1EKcmRPNU
    1Vc0gxd2U2ejlVbHJKOHd0bzAwVHBDUi9lRndKb2RWZ1RKL05Pd21INWtEbktiQUNtRVRp
    Q0RZbGEyMwo0YjQ1SmZvQzFuc1JCdUxIc2Fua2tBPT0KLS0tLS1FTkQgRU5DUllQVEVEIF
    BSSVZBVEUgS0VZLS0tLS0K
  1x-hostapd.example.com.pem: |
    Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgIC
    AgICBTZXJpYWwgTnVtYmVyOgogICAgICAgICAgICA4ZjpkYjowNTo1YTpiYzpiNjowNDpm
    ZDo3ODphMToxNjo5NDplMTo0NjowMDpmZQogICAgICAgIFNpZ25hdHVyZSBBbGdvcml0aG
    06IHNoYTI1NldpdGhSU0FFbmNyeXB0aW9uCiAgICAgICAgSXNzdWVyOiBDTj1kY2FyYXR0
    aQogICAgICAgIFZhbGlkaXR5CiAgICAgICAgICAgIE5vdCBCZWZvcmU6IEphbiAxMyAwOT
    owMDozMCAyMDIyIEdNVAogICAgICAgICAgICBOb3QgQWZ0ZXIgOiBBcHIgMTcgMDk6MDA6
    MzAgMjAyNCBHTVQKICAgICAgICBTdWJqZWN0OiBDTj0xeC1ob3N0YXBkLmV4YW1wbGUuY2
    9tCiAgICAgICAgU3ViamVjdCBQdWJsaWMgS2V5IEluZm86CiAgICAgICAgICAgIFB1Ymxp
    YyBLZXkgQWxnb3JpdGhtOiByc2FFbmNyeXB0aW9uCiAgICAgICAgICAgICAgICBSU0EgUH
    VibGljLUtleTogKDIwNDggYml0KQogICAgICAgICAgICAgICAgTW9kdWx1czoKICAgICAg
    ICAgICAgICAgICAgICAwMDphZjo4Mzo2OTo3OTozYzplNTo0Mzo0Zjo4NjpiNjo2ZjplZj
    o1ODpmODoKICAgICAgICAgICAgICAgICAgICAyYzo3ZDpiMDo5MDpkNzo4Nzo3ODoxYzpl
    MTo3NjoyNjo0YTo3MjozYTpkZjoKICAgICAgICAgICAgICAgICAgICA2ZDpmZTpjMDo1ZD
    o4Yjo1ZTpjZToxNDoxMzoxNzplZTo3MTphZjpiNzoyYToKICAgICAgICAgICAgICAgICAg
    ICAwMjowMjoxYTozYzphMTo2YTpjYjoyYzowYzoyZDpkYzpmYjozZjo0MDo2ZjoKICAgIC
    AgICAgICAgICAgICAgICAxMTo1YTozZjoyYjpjNzo4Yjo2NDozOTpiNTo5OTo5NDpiMDpm
    Nzo3ZTplNjoKICAgICAgICAgICAgICAgICAgICA0ZTo0ZToxMTo3Mjo2YjpkMDoxMDo5Yz
    phYzo0YjpjOTphYzoyODpkNDpkNDoKICAgICAgICAgICAgICAgICAgICAyZTo2MDo0YTpi
    YzpmZTozMzpkNToxMDozYzo0ZDowMDplODpjNzplZDo0ODoKICAgICAgICAgICAgICAgIC
    AgICAzOTo3MTphZjoxNzo1YTplNzo5MTpjODpkZjpkMzoxMTpkZjo1NDoyNjpmNjoKICAg
    ICAgICAgICAgICAgICAgICBhMTplZTo1NTpmODo2NjpkYjplNDo3NTpjNzo4NjoyMjpmYT
    owODo3NDo5OToKICAgICAgICAgICAgICAgICAgICAzYTo4MDo0MDowMzo5ZDpmNjo3Zjpl
    MTo5Zjo1OTpmODpjNDoyZDoxNzo0YzoKICAgICAgICAgICAgICAgICAgICAxNzo5MTo0OD
    o3MzpiZDplNTo0MjpmNjoxOTphNDpiNTowZjoyMzo3ZToxNjoKICAgICAgICAgICAgICAg
    ICAgICA1MDoyMDoxNTowOTo2Mzo5ZjoxNjoxMjo1YjpjZjo4YTozODoyNzplYzphMjoKIC
    AgICAgICAgICAgICAgICAgICA1Yzo3MDowYzpiZDowZDo0MzozNzo4OToyMzpjNDoxMTo4
    ZDo4MTo0Zjo1MToKICAgICAgICAgICAgICAgICAgICBjMTpkNjoyZjowMTplNzo0ZTpiZT
    plYzo3NzowOTo0NTphMzo1MzplZToyZjoKICAgICAgICAgICAgICAgICAgICAzODo3NTo3
    Yjo2YzoyODphYjowZjpiYTo4ODo2MTo2YjoxNDpjZTo3Yzo3MDoKICAgICAgICAgICAgIC
    AgICAgICBlZTphNDo2Zjo4NDo0ODpmNTowMjplYzo1ZTowZDo2MToxNzowZjo1MTozNzoK
    ICAgICAgICAgICAgICAgICAgICBmMTo4MjoyOTo4MDphOToxYzo4YzphMzowOToxODo5ZT
    o0MzpjMjo4ODplNToKICAgICAgICAgICAgICAgICAgICA4YTpjNQogICAgICAgICAgICAg
    ICAgRXhwb25lbnQ6IDY1NTM3ICgweDEwMDAxKQogICAgICAgIFg1MDl2MyBleHRlbnNpb2
    5zOgogICAgICAgICAgICBYNTA5djMgQmFzaWMgQ29uc3RyYWludHM6IAogICAgICAgICAg
    ICAgICAgQ0E6RkFMU0UKICAgICAgICAgICAgWDUwOXYzIFN1YmplY3QgS2V5IElkZW50aW
    ZpZXI6IAogICAgICAgICAgICAgICAgNDA6Mzk6QUI6MDA6M0Q6QkY6REU6NUE6NUE6Q0E6
    MDM6MzU6NTI6ODM6NkI6QTM6MEI6MEI6RjA6QkMKICAgICAgICAgICAgWDUwOXYzIEF1dG
    hvcml0eSBLZXkgSWRlbnRpZmllcjogCiAgICAgICAgICAgICAgICBrZXlpZDo1NTo2ODo4
    OTo5QTpDQzpGRjpDRDpFODoyODo5ODpBQzpFQzpCQjo3RTpEMzoxRjpBNjpBRTpCMzpERQ
    ogICAgICAgICAgICAgICAgRGlyTmFtZTovQ049ZGNhcmF0dGkKICAgICAgICAgICAgICAg
    IHNlcmlhbDo0ODpCRTpFRjpCQzoyNTowQTpCRjpDQTo2OTozQzpERjo1OTpFMzo3NzoxQz
    o1MDpBQzo2MDo1QjpGMgoKICAgICAgICAgICAgWDUwOXYzIEV4dGVuZGVkIEtleSBVc2Fn
    ZTogCiAgICAgICAgICAgICAgICBUTFMgV2ViIFNlcnZlciBBdXRoZW50aWNhdGlvbgogIC
    AgICAgICAgICBYNTA5djMgS2V5IFVzYWdlOiAKICAgICAgICAgICAgICAgIERpZ2l0YWwg
    U2lnbmF0dXJlLCBLZXkgRW5jaXBoZXJtZW50CiAgICAgICAgICAgIFg1MDl2MyBTdWJqZW
    N0IEFsdGVybmF0aXZlIE5hbWU6IAogICAgICAgICAgICAgICAgRE5TOjF4LWhvc3RhcGQu
    ZXhhbXBsZS5jb20KICAgIFNpZ25hdHVyZSBBbGdvcml0aG06IHNoYTI1NldpdGhSU0FFbm
    NyeXB0aW9uCiAgICAgICAgIDM5OjUwOjViOmEyOjY4OmNlOmIwOjhkOjc5OjM2OmRjOmVh
    OmU5OjkwOmUyOjgzOjQxOmI2OgogICAgICAgICAyMDo5Mjo2NjpjNDowZjo0NTo5NjoyNT
    pmMjpmZjpkYjo5ZDowODo4NDpjZTozNjo4NDpmMzoKICAgICAgICAgNmM6NWU6NzE6Mjc6
    ZTc6Y2Q6OWE6YWI6NmE6NzU6NjM6ZDM6NzI6Zjc6MzY6ODU6OWE6ZGY6CiAgICAgICAgID
    YyOjBhOmVlOjdkOjQwOmI5OjBlOjUzOjllOmI1OjYzOjdlOjdjOjc3OjNiOjAxOjlkOjVi
    OgogICAgICAgICA3NDpmNzoyYzowMzphOTpmZDplMzpkMTozYzowNzpiMDoxYjpmYzo4Nz
    o3MTpiOTowZDo2ODoKICAgICAgICAgOTA6ZTA6OWM6OWM6N2E6OTU6ZjU6ZTM6MjE6MmQ6
    ZmE6YTg6OTA6NmQ6ZDc6MDI6NTI6Mzc6CiAgICAgICAgIDY5OjQ1OjllOjRkOmYxOmZkOj
    k1OmFlOmQxOjhmOjkyOjM3OjIzOmM4OmQ2OmJjOmI1OmI0OgogICAgICAgICA0OTo1ODph
    ZjpjMDozMjo0YjowMDoxMDplNTo5MTo4Nzo0ZTo1YTplYzo5Njo2MTo2ODoxMToKICAgIC
    AgICAgNTc6ZjA6ZmM6MTc6OWM6OTA6OGM6Mzg6MmE6OWY6NTM6OGM6YTA6Y2I6Yjk6ZWI6
    NWU6NDg6CiAgICAgICAgIDk1OjUyOmE2OjBlOjY0Ojg5OmVmOmJlOjFiOjRlOjg2OjQ2Oj
    M3OjliOmE1OjlkOjg3OmFiOgogICAgICAgICAxZjo0NzpkYzo1ZDo0MzowNDplYTpjYjpm
    Mjo1YjoxZjoxNTo5NjpiNToxZDoyMjpkZDo0NDoKICAgICAgICAgMjI6ZmY6NjI6ZGU6Mz
    Y6MmQ6YTY6OGE6YjA6ZDE6MDM6M2Q6Y2Q6ZDM6NTc6ZjQ6YTI6OTA6CiAgICAgICAgIDYw
    OmQzOjFhOjU1OjNkOjI2OjEzOjI1OjQxOjkzOmVkOjU3OjMzOmJjOmY1OjcxOjdmOjk0Og
    ogICAgICAgICAxMjpmNzowMzo0Yjo1Yzo0NDplNjo4NDo0NTphZjplNDpiNjpkNTo4Nzoz
    MDo5YjowNzpmNDoKICAgICAgICAgZmE6YzY6Nzc6MDYKLS0tLS1CRUdJTiBDRVJUSUZJQ0
    FURS0tLS0tCk1JSURnakNDQW1xZ0F3SUJBZ0lSQUkvYkJWcTh0Z1Q5ZUtFV2xPRkdBUDR3
    RFFZSktvWklodmNOQVFFTEJRQXcKRXpFUk1BOEdBMVVFQXd3SVpHTmhjbUYwZEdrd0hoY0
    5Nakl3TVRFek1Ea3dNRE13V2hjTk1qUXdOREUzTURrdwpNRE13V2pBaE1SOHdIUVlEVlFR
    RERCWXhlQzFvYjNOMFlYQmtMbVY0WVcxd2JHVXVZMjl0TUlJQklqQU5CZ2txCmhraUc5dz
    BCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcjROcGVUemxRMCtHdG0vdldQZ3NmYkNRMTRk
    NEhPRjIKSmtweU90OXQvc0JkaTE3T0ZCTVg3bkd2dHlvQ0FobzhvV3JMTEF3dDNQcy9RRz
    hSV2o4cng0dGtPYldabExEMwpmdVpPVGhGeWE5QVFuS3hMeWF3bzFOUXVZRXE4L2pQVkVE
    eE5BT2pIN1VnNWNhOFhXdWVSeU4vVEVkOVVKdmFoCjdsWDRadHZrZGNlR0l2b0lkSms2Z0
    VBRG5mWi80WjlaK01RdEYwd1hrVWh6dmVWQzlobWt0UThqZmhaUUlCVUoKWTU4V0VsdlBp
    amduN0tKY2NBeTlEVU0zaVNQRUVZMkJUMUhCMWk4QjUwNis3SGNKUmFOVDdpODRkWHRzS0
    tzUAp1b2hoYXhUT2ZIRHVwRytFU1BVQzdGNE5ZUmNQVVRmeGdpbUFxUnlNb3drWW5rUENp
    T1dLeFFJREFRQUJvNEhDCk1JRy9NQWtHQTFVZEV3UUNNQUF3SFFZRFZSME9CQllFRkVBNX
    F3QTl2OTVhV3NvRE5WS0RhNk1MQy9DOE1FNEcKQTFVZEl3UkhNRVdBRkZWb2lack0vODNv
    S0ppczdMdCsweCttcnJQZW9SZWtGVEFUTVJFd0R3WURWUVFEREFoawpZMkZ5WVhSMGFZSV
    VTTDd2dkNVS3Y4cHBQTjlaNDNjY1VLeGdXL0l3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVI
    CkF3RXdDd1lEVlIwUEJBUURBZ1dnTUNFR0ExVWRFUVFhTUJpQ0ZqRjRMV2h2YzNSaGNHUX
    VaWGhoYlhCc1pTNWoKYjIwd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEbFFXNkpvenJD
    TmVUYmM2dW1RNG9OQnRpQ1Nac1FQUlpZbAo4di9iblFpRXpqYUU4MnhlY1NmbnpacXJhbl
    ZqMDNMM05vV2EzMklLN24xQXVRNVRuclZqZm54M093R2RXM1QzCkxBT3AvZVBSUEFld0cv
    eUhjYmtOYUpEZ25KeDZsZlhqSVMzNnFKQnQxd0pTTjJsRm5rM3gvWld1MFkrU055UEkKMX
    J5MXRFbFlyOEF5U3dBUTVaR0hUbHJzbG1Gb0VWZncvQmVja0l3NEtwOVRqS0RMdWV0ZVNK
    VlNwZzVraWUrKwpHMDZHUmplYnBaMkhxeDlIM0YxREJPckw4bHNmRlphMUhTTGRSQ0wvWX
    Q0MkxhYUtzTkVEUGMzVFYvU2lrR0RUCkdsVTlKaE1sUVpQdFZ6Tzg5WEYvbEJMM0EwdGNS
    T2FFUmEva3R0V0hNSnNIOVByR2R3WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  hostapd.eap_user: |
    IyBob3N0YXBkIHVzZXIgZGF0YWJhc2UgZm9yIGludGVncmF0ZWQgRUFQIHNlcnZlcgoKIy
    BFYWNoIGxpbmUgbXVzdCBjb250YWluIGFuIGlkZW50aXR5LCBFQVAgbWV0aG9kKHMpLCBh
    bmQgYW4gb3B0aW9uYWwgcGFzc3dvcmQKIyBzZXBhcmF0ZWQgd2l0aCB3aGl0ZXNwYWNlIC
    hzcGFjZSBvciB0YWIpLiBUaGUgaWRlbnRpdHkgYW5kIHBhc3N3b3JkIG11c3QgYmUKIyBk
    b3VibGUgcXVvdGVkICgidXNlciIpLiBQYXNzd29yZCBjYW4gYWx0ZXJuYXRpdmVseSBiZS
    BzdG9yZWQgYXMKIyBOdFBhc3N3b3JkSGFzaCAoMTYtYnl0ZSBNRDQgaGFzaCBvZiB0aGUg
    dW5pY29kZSBwcmVzZW50YXRpb24gb2YgdGhlIHBhc3N3b3JkCiMgaW4gdW5pY29kZSkgaW
    YgaXQgaXMgdXNlZCBmb3IgTVNDSEFQIG9yIE1TQ0hBUHYyIGF1dGhlbnRpY2F0aW9uLiBU
    aGlzIG1lYW5zCiMgdGhhdCB0aGUgcGxhaW50ZXh0IHBhc3N3b3JkIGRvZXMgbm90IG5lZW
    QgdG8gYmUgaW5jbHVkZWQgaW4gdGhlIHVzZXIgZmlsZS4KIyBQYXNzd29yZCBoYXNoIGlz
    IHN0b3JlZCBhcyBoYXNoOjwxNi1vY3RldHMgb2YgaGV4IGRhdGE+IHdpdGhvdXQgcXVvdG
    F0aW9uCiMgbWFya3MuCgojIFsyXSBmbGFnIGluIHRoZSBlbmQgb2YgdGhlIGxpbmUgY2Fu
    IGJlIHVzZWQgdG8gbWFyayB1c2VycyBmb3IgdHVubmVsZWQgcGhhc2UKIyAyIGF1dGhlbn
    RpY2F0aW9uIChlLmcuLCB3aXRoaW4gRUFQLVBFQVApLiBJbiB0aGVzZSBjYXNlcywgYW4g
    YW5vbnltb3VzCiMgaWRlbnRpdHkgY2FuIGJlIHVzZWQgaW4gdGhlIHVuZW5jcnlwdGVkIH
    BoYXNlIDEgYW5kIHRoZSByZWFsIHVzZXIgaWRlbnRpdHkKIyBpcyB0cmFuc21pdHRlZCBv
    bmx5IHdpdGhpbiB0aGUgZW5jcnlwdGVkIHR1bm5lbCBpbiBwaGFzZSAyLiBJZiBub24tYW
    5vbnltb3VzCiMgYWNjZXNzIGlzIG5lZWRlZCwgdHdvIHVzZXIgZW50cmllcyBpcyBuZWVk
    ZWQsIG9uZSBmb3IgcGhhc2UgMSBhbmQgYW5vdGhlcgojIHdpdGggdGhlIHNhbWUgdXNlcm
    5hbWUgZm9yIHBoYXNlIDIuCiMKIyBFQVAtVExTLCBFQVAtUEVBUCwgRUFQLVRUTFMsIEVB
    UC1GQVNULCBFQVAtU0lNLCBhbmQgRUFQLUFLQSBkbyBub3QgdXNlCiMgcGFzc3dvcmQgb3
    B0aW9uLgojIEVBUC1NRDUsIEVBUC1NU0NIQVBWMiwgRUFQLUdUQywgRUFQLVBBWCwgRUFQ
    LVBTSywgYW5kIEVBUC1TQUtFIHJlcXVpcmUgYQojIHBhc3N3b3JkLgojIEVBUC1QRUFQLC
    BFQVAtVFRMUywgYW5kIEVBUC1GQVNUIHJlcXVpcmUgUGhhc2UgMiBjb25maWd1cmF0aW9u
    LgojCiMgKiBjYW4gYmUgdXNlZCBhcyBhIHdpbGRjYXJkIHRvIG1hdGNoIGFueSB1c2VyIG
    lkZW50aXR5LiBUaGUgbWFpbiBwdXJwb3NlcyBmb3IKIyB0aGlzIGFyZSB0byBzZXQgYW5v
    bnltb3VzIHBoYXNlIDEgaWRlbnRpdHkgZm9yIEVBUC1QRUFQIGFuZCBFQVAtVFRMUyBhbm
    QgdG8KIyBhdm9pZCBoYXZpbmcgdG8gY29uZmlndXJlIGV2ZXJ5IGNlcnRpZmljYXRlIGZv
    ciBFQVAtVExTIGF1dGhlbnRpY2F0aW9uLiBUaGUKIyBmaXJzdCBtYXRjaGluZyBlbnRyeS
    BpcyBzZWxlY3RlZCwgc28gKiBzaG91bGQgYmUgdXNlZCBhcyB0aGUgbGFzdCBwaGFzZSAx
    CiMgdXNlciBlbnRyeS4KIwojICJwcmVmaXgiKiBjYW4gYmUgdXNlZCB0byBtYXRjaCB0aG
    UgZ2l2ZW4gcHJlZml4IGFuZCBhbnl0aGluZyBhZnRlciB0aGlzLiBUaGUKIyBtYWluIHB1
    cnBvc2UgZm9yIHRoaXMgaXMgdG8gYmUgYWJsZSB0byBhdm9pZCBFQVAgbWV0aG9kIG5lZ2
    90aWF0aW9uIHdoZW4gdGhlCiMgbWV0aG9kIGlzIHVzaW5nIGtub3duIHByZWZpeCBpbiBp
    ZGVudGl0aWVzIChlLmcuLCBFQVAtU0lNIGFuZCBFQVAtQUtBKS4gVGhpcwojIGlzIG9ubH
    kgYWxsb3dlZCBmb3IgcGhhc2UgMSBpZGVudGl0aWVzLgojCiMgTXVsdGlwbGUgbWV0aG9k
    cyBjYW4gYmUgY29uZmlndXJlZCB0byBtYWtlIHRoZSBhdXRoZW50aWNhdG9yIHRyeSB0aG
    VtIG9uZSBieQojIG9uZSB1bnRpbCB0aGUgcGVlciBhY2NlcHRzIG9uZS4gVGhlIG1ldGhv
    ZCBuYW1lcyBhcmUgc2VwYXJhdGVkIHdpdGggYQojIGNvbW1hICgsKS4KIwojIFt2ZXI9MF
    0gYW5kIFt2ZXI9MV0gZmxhZ3MgYWZ0ZXIgRUFQIHR5cGUgUEVBUCBjYW4gYmUgdXNlZCB0
    byBmb3JjZSBQRUFQCiMgdmVyc2lvbiBiYXNlZCBvbiB0aGUgUGhhc2UgMSBpZGVudGl0eS
    4gV2l0aG91dCB0aGlzIGZsYWcsIHRoZSBFQVAKIyBhdXRoZW50aWNhdG9yIGFkdmVydGlz
    ZXMgdGhlIGhpZ2hlc3Qgc3VwcG9ydGVkIHZlcnNpb24gYW5kIHNlbGVjdCB0aGUgdmVyc2
    lvbgojIGJhc2VkIG9uIHRoZSBmaXJzdCBQRUFQIHBhY2tldCBmcm9tIHRoZSBzdXBwbGlj
    YW50LgojCiMgRUFQLVRUTFMgc3VwcG9ydHMgYm90aCBFQVAgYW5kIG5vbi1FQVAgYXV0aG
    VudGljYXRpb24gaW5zaWRlIHRoZSB0dW5uZWwuCiMgVHVubmVsZWQgRUFQIG1ldGhvZHMg
    YXJlIGNvbmZpZ3VyZWQgd2l0aCBzdGFuZGFyZCBFQVAgbWV0aG9kIG5hbWUgYW5kIFsyXQ
    ojIGZsYWcuIE5vbi1FQVAgbWV0aG9kcyBjYW4gYmUgZW5hYmxlZCBieSBmb2xsb3dpbmcg
    bWV0aG9kIG5hbWVzOiBUVExTLVBBUCwKIyBUVExTLUNIQVAsIFRUTFMtTVNDSEFQLCBUVE
    xTLU1TQ0hBUFYyLiBUVExTLVBBUCBhbmQgVFRMUy1DSEFQIHJlcXVpcmUgYQojIHBsYWlu
    dGV4dCBwYXNzd29yZCB3aGlsZSBUVExTLU1TQ0hBUCBhbmQgVFRMUy1NU0NIQVBWMiBjYW
    4gdXNlIE5UIHBhc3N3b3JkCiMgaGFzaC4KIwojIEFyYml0cmFyeSBSQURJVVMgYXR0cmli
    dXRlcyBjYW4gYmUgYWRkZWQgaW50byBBY2Nlc3MtQWNjZXB0IHBhY2tldHMgc2ltaWxhcm
    x5CiMgdG8gdGhlIHdheSByYWRpdXNfYXV0aF9yZXFfYXR0ciBpcyB1c2VkIGZvciBBY2Nl
    c3MtUmVxdWVzdCBwYWNrZXQgaW4KIyBob3N0YXBkLmNvbmYuIEZvciBFQVAgc2VydmVyLC
    B0aGlzIGlzIGNvbmZpZ3VyZWQgc2VwYXJhdGVseSBmb3IgZWFjaCB1c2VyCiMgZW50cnkg
    d2l0aCByYWRpdXNfYWNjZXB0X2F0dHI9PHZhbHVlPiBsaW5lKHMpIGZvbGxvd2luZyB0aG
    UgbWFpbiB1c2VyIGVudHJ5CiMgbGluZS4KCiMgUGhhc2UgMSB1c2VycwoidXNlciIJCU1E
    NQkicGFzc3dvcmQiCiJ0ZXN0IHVzZXIiCU1ENQkic2VjcmV0IgoiZXhhbXBsZSB1c2VyIg
    lUTFMKIkRPTUFJTlx1c2VyIglNU0NIQVBWMgkicGFzc3dvcmQiCiJndGMgdXNlciIJR1RD
    CSJwYXNzd29yZCIKIyJwYXggdXNlciIJUEFYCSJ1bmtub3duIgojInBheC51c2VyQGV4YW
    1wbGUuY29tIglQQVgJMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYKIyJwc2sg
    dXNlciIJUFNLCSJ1bmtub3duIgojInBzay51c2VyQGV4YW1wbGUuY29tIglQU0sJMDEyMz
    Q1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYKIyJzYWtlLnVzZXJAZXhhbXBsZS5jb20i
    CVNBS0UJMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZG
    VmMDEyMzQ1Njc4OWFiY2RlZgoidHRscyIJCVRUTFMKIm5vdCBhbm9ueW1vdXMiCVBFQVAK
    IyBEZWZhdWx0IHRvIEVBUC1TSU0gYW5kIEVBUC1BS0EgYmFzZWQgb24gZml4ZWQgaWRlbn
    RpdHkgcHJlZml4ZXMKIyIwIioJCVRUTFMsVExTLFBFQVAsU0lNCiMiMSIqCQlTSU0sVFRM
    UyxUTFMsUEVBUAojIjIiKgkJVFRMUyxUTFMsUEVBUCxTSU0KIyIzIioJCVNJTSxUVExTLF
    RMUyxQRUFQCiMiNCIqCQlUVExTLFRMUyxQRUFQLFNJTQojIjUiKgkJU0lNLFRUTFMsVExT
    LFBFQVAKIyI2IioJCUFLQScKIyI3IioJCUFLQScKIyI4IioJCUFLQScKCiJ1c2VyQGV4YW
    1wbGUuY29tIiBUTFMgInNlY3JldDEyMyIKCiMgV2lsZGNhcmQgZm9yIGFsbCBvdGhlciBp
    ZGVudGl0aWVzCiMqCQlQRUFQLFRUTFMsVExTLFNJTQoKIyBQaGFzZSAyICh0dW5uZWxsZW
    Qgd2l0aGluIEVBUC1QRUFQIG9yIEVBUC1UVExTKSB1c2VycwoidC1tZDUiCQlNRDUJInBh
    c3N3b3JkIglbMl0KIkRPTUFJTlx0LW1zY2hhcHYyIglNU0NIQVBWMgkicGFzc3dvcmQiCV
    syXQoidC1ndGMiCQlHVEMJInBhc3N3b3JkIglbMl0KIm5vdCBhbm9ueW1vdXMiCU1TQ0hB
    UFYyCSJwYXNzd29yZCIJWzJdCiJ1c2VyIgkJTUQ1LEdUQyxNU0NIQVBWMgkicGFzc3dvcm
    QiCVsyXQoidGVzdCB1c2VyIglNU0NIQVBWMgloYXNoOjAwMDEwMjAzMDQwNTA2MDcwODA5
    MGEwYjBjMGQwZTBmCVsyXQoidHRscy11c2VyIglUVExTLVBBUCxUVExTLUNIQVAsVFRMUy
    1NU0NIQVAsVFRMUy1NU0NIQVBWMgkicGFzc3dvcmQiCVsyXQoKIyBEZWZhdWx0IHRvIEVB
    UC1TSU0gYW5kIEVBUC1BS0EgYmFzZWQgb24gZml4ZWQgaWRlbnRpdHkgcHJlZml4ZXMgaW
    4gcGhhc2UgMgojIjAiKgkJQUtBCVsyXQojIjEiKgkJU0lNCVsyXQojIjIiKgkJQUtBCVsy
    XQojIjMiKgkJU0lNCVsyXQojIjQiKgkJQUtBCVsyXQojIjUiKgkJU0lNCVsyXQojIjYiKg
    kJQUtBJwlbMl0KIyI3IioJCUFLQScJWzJdCiMiOCIqCQlBS0EnCVsyXQo=
  hostapd.radius_clients: MC4wLjAuMC8wIHRlc3RpbmcxMjMK
kind: Secret
metadata:
  name: localauth-2hcbd4mg4m
type: Opaque
