# permissions for end users to view authenticators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authenticator-viewer-role
rules:
- apiGroups:
  - eapol.eapol.openshift.io
  resources:
  - authenticators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eapol.eapol.openshift.io
  resources:
  - authenticators/status
  verbs:
  - get
