apiVersion: eapol.eapol.openshift.io/v1
kind: Authenticator
metadata:
  name: authenticator-sample
spec:
  interfaces: [ "eth0" ]
  authentication:
    local:
      userFileSecret:
        name: "localauth"
      caCertSecret:
        name: "localauth"
      serverCertSecret:
        name: "localauth"
      privateKeySecret:
        name: "localauth"
      privateKeyPassphrase: "Hsecret"
      radiusClientFileSecret:
        name: "localauth"
