## Append samples you want in your CSV to this file as resources ##
resources:
- eapol_v1_authenticator.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
secretGenerator:
- name: localauth
  files:
  - hostapd.eap_user

configurations:
- kustomizeconfig/authenticator.yaml
