## Append samples you want in your CSV to this file as resources ##
resources:
- eapol_v1_authenticator.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
secretGenerator:
- name: localauth
  files:
  - hostapd.eap_user
  - hostapd.radius_clients
  - certs/1x-ca.pem
  - certs/1x-hostapd.example.com.key
  - certs/1x-hostapd.example.com.pem

configurations:
- kustomizeconfig/authenticator.yaml
